# Generated by Django 4.2 on 2023-06-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cr_dist1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cr_dist2',
        ),
    ]
