# Generated by Django 4.2 on 2023-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0007_alter_activity_c_id_alter_activity_p_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apname', models.CharField(max_length=40)),
                ('aptime', models.DateTimeField()),
                ('dr_name', models.CharField(max_length=50)),
                ('h_name', models.CharField(max_length=100)),
                ('p_id', models.IntegerField()),
                ('c_id', models.IntegerField()),
            ],
        ),
    ]
