# Generated by Django 4.2 on 2023-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0008_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=200)),
                ('mtype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=250)),
                ('m_cat', models.CharField(max_length=100)),
                ('cons_time', models.DateTimeField()),
                ('p_id', models.IntegerField()),
                ('c_id', models.IntegerField()),
            ],
        ),
    ]
