# Generated by Django 4.2 on 2023-06-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0009_medicine_medicine_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_details',
            name='cons_time',
            field=models.TimeField(),
        ),
    ]
