# Generated by Django 4.2 on 2023-06-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0010_alter_medicine_details_cons_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='aptime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='c_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dr_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='h_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='p_id',
            field=models.IntegerField(null=True),
        ),
    ]
