# Generated by Django 4.2 on 2023-06-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0011_appointment_status_alter_appointment_apname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='aname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='astatus',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='c_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='p_id',
            field=models.IntegerField(null=True),
        ),
    ]
